### ISSUE TITLE
Paul Zobs, Web Dev II 020

### ISSUE THREAD

**Issue by paulzobs** [paulzobs/hear-me-oh-content#1]
Markbots saying I'm using content info more than once when Im pretty sure I'm not.
<img width="528" alt="Screen Shot 2020-10-06 at 1 30 44 PM" src="https://user-images.githubusercontent.com/55509579/95239280-b5d68f80-07d8-11eb-8b27-0676b7ef8955.png">
@MacKenzieRose @hellachella

**Comment by MacKenzieRose** [comment]
Hey! 

So what Markbot is telling you is that it needs to see `role="contentinfo"` somewhere in your index file, but only once. It looks like you haven't used it yet, but once you do, that error should resolve itself. 😄

**Comment by hellachella** [comment]
@paulzobs You need to add yourself to the Progressinator ASAP!!

**Comment by hellachella** [comment]
@MacKenzieRose would you mind helping make sure @paulzobs  gets his API key into the Progressinator.

**Comment by paulzobs** [comment]
sorry I thought I already was, where do I do that?

**Comment by MacKenzieRose** [comment]
Via the Progress side of the Learn the Web (see screenshot):

<img width="1516" alt="Screen Shot 2020-10-07 at 9 36 14 AM" src="https://user-images.githubusercontent.com/19557909/95345733-aa3ea380-0880-11eb-8e08-1cff86f2b10d.png">

Once you're logged in with your Github account there, click on your username (top right corner), and make sure you have selected your course and section (see screenshot):

<img width="761" alt="Screen Shot 2020-10-07 at 9 39 13 AM" src="https://user-images.githubusercontent.com/19557909/95346069-0a354a00-0881-11eb-808f-192699f690ef.png">

If you've completed all of that, let me know, and we'll continue troubleshooting it 🙂

**Comment by hellachella** [comment]
https://learn-the-web.algonquindesign.ca/courses/web-design-1/install-all-the-things/

scroll to the last bullet

**Comment by paulzobs** [comment]
shawggggg I got it, sorry cause I could still see all the assignments I thought I was in.

**Comment by MacKenzieRose** [comment]
Awesome~ everything working on your end, @hellachella ?
